### ISSUE TITLE
conflict with slash command

### ISSUE THREAD

**Issue by lifesign** [tadashi-aikawa/obsidian-various-complements-plugin#49] opened 2021-12-16 07:40 UTC
it seems obsidian core plugin "Slash commands" was broken when various complements plugin was enabled. conflicted?

**Comment by tadashi-aikawa** [comment] 2021-12-16 11:46
@lifesign 
What version do you use?

**Comment by tadashi-aikawa** [comment] 2021-12-18 02:58
I could reproduce it 👍

**Comment by tadashi-aikawa** [comment] 2021-12-18 04:19
@lifesign 
I have released to [v3.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.0) 🚀

Please confirm whether it works as you expected.

**Comment by lifesign** [comment] 2021-12-18 12:18
seems ok, thx~

**Comment by keithadams** [comment] 2022-01-14 23:16
I'm having this problem still. Using a fresh vault with slash commands enabled and Various Complements installed.

Create a note titled 'Internal Link'. Then type `/int` for the **Add Internal Link** command.

1. Typing `/in` will show Slash commands
2. Typing `/int` will show only VC

**Versions:**
- Obsidian 0.13.19
- VC 4.2.0

**Comment by tadashi-aikawa** [comment] 2022-01-15 03:18
@keithadams

Thanks. I could reproduce it.

But, strangely, it occurs only in a new vault. I couldn't reproduce it in my main vault... 🤔

**Comment by keithadams** [comment] 2022-01-15 07:11
@tadashi-aikawa 

Interesting, I was having the problem on my main vault as well.

I installed the beta and it's fixed. Thank you very much!

**Comment by tadashi-aikawa** [comment] 2022-01-15 07:13
Thank you for your confirmation!

I will close this issue after release v5.0.0.

**Comment by tadashi-aikawa** [comment] 2022-01-23 11:02
I have released to [v5.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.0.0) 🚀

So closed this issue.

**Closed by tadashi-aikawa** 2022-01-23 11:02 UTC
Labels: enhancement
