### ISSUE TITLE
Does the word selection interface consider adding a page turning function, like the input method?

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#8] opened 2021-10-31 08:24 UTC
I have been using this plugin for a few months and it has helped me a lot, thanks to the developer!

in addition , Does the word selection interface consider adding a page turning function, like the input method?

**Comment by tadashi-aikawa** [comment] 2021-10-31 10:01
Hi, @tyf2018. Thank you for creating a issue!

> Does the word selection interface consider adding a page turning function, like the input method?

I have confirmed the behavior, and I noticed that it might need to adapt for migrating from CodeMirror 5 to 6 (about Obsidian) before implementing this issue.

Therefore I keep this issue open and start when I can implement it.

**Comment by tadashi-aikawa** [comment] 2021-11-17 10:57
@tyf2018 
I have released as [v1.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.1.0). 🚀 

![image](https://user-images.githubusercontent.com/9500018/142187564-1368c4eb-5168-4f4e-9419-d2e3146b614e.png)

**Comment by tyf2018** [comment] 2021-11-18 01:11
The latest version seems to be unavailable in the Chinese environment.

In fact, after someone pointed me, I modified the 0.4.0 version of the main.js file, the main purpose is to add custom words, and it works well. Something like this:
![2021-11-18_09-00-00](https://user-images.githubusercontent.com/56342788/142331842-d06fab28-3899-4b09-81ba-493be2d9b7ee.jpg)

Here is the 0.4.0 version of the main.js file:
[main.zip](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/files/7559008/main.zip)

I want to understand these three questions: 
1. How can I add custom words in the new version of the plug-in? 
2. There are generally no spaces in Chinese. How can the plug-in automatically recognize and pop up candidate words? I don't quite understand, and I don't know how to set it up. 
3. If there are too many candidate words (maybe more than 100), is there a way to turn the page, like input method software?

Looking forward to the answer, thank you!

**Comment by tadashi-aikawa** [comment] 2021-11-18 08:58
Hi, @tyf2018.

> The latest version seems to be unavailable in the Chinese environment.

It doesn't show suggestions if your input char less than 2 (ex: `测` ). However, I'll add a options `Minimum number of characters for trigger`. (You can set it 1)

> How can I add custom words in the new version of the plug-in?

No, not yet. However, I'll add this feature as soon as possible :) (See https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/12)

> There are generally no spaces in Chinese. How can the plug-in automatically recognize and pop up candidate words? I don't quite understand, and I don't know how to set it up.

It doesn't support Chinese yet. However, if I close https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/7, you can probably auto-complete considering the grammar of Chinese.

> If there are too many candidate words (maybe more than 100), is there a way to turn the page, like input method software?

Does `input method software` mean like an `MS-IME`?  If so, I think it may be more suitable to use IME. (I'm sorry if I said something wrong because I have never used IME to write Chinese)

Best regards.

**Comment by tyf2018** [comment] 2021-11-18 10:31
Hi， @tadashi-aikawa ，thanks for the reply.

> Does input method software mean like an MS-IME? If so, I think it may be more suitable to use IME. (I'm sorry if I said something wrong because I have never used IME to write Chinese)

Yes, it is similar to MS IME. In fact, what I mean is: when adding custom words (more than 1 million in total), there will be a lot of candidate words, then when an interface cannot be displayed in full, can the user press the shortcut key to turn the page to view Complete candidate words. The action of "turning pages" is somewhat similar to the operation in MS IME.

**Comment by tadashi-aikawa** [comment] 2021-11-18 10:56
@tyf2018 
Thank you for your explanation. I understood what you wanted to say.

I don't know whether it is possible or not, but I try it :)

**Comment by tadashi-aikawa** [comment] 2021-11-18 11:44
@tyf2018 

I have surveyed whether it is possible or not. Unfortunately, it seems to be impossible without creating Suggest class from scratch.

Therefore, I will close this issue. If it is possible someday, I will reopen this.

Best regards.

**Closed by tadashi-aikawa** 2021-11-18 11:44 UTC
Labels: enhancement

**Comment by tadashi-aikawa** [comment] 2021-11-18 14:55
@tyf2018 

>> How can I add custom words in the new version of the plug-in?
> No, not yet. However, I'll add this feature as soon as possible :) (See #12)

Maybe, this is coming soon! --> https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/12#issuecomment-972939189
