### ISSUE TITLE
Unable to edit options or see it in the settings panel

### ISSUE THREAD

**Issue by crazymedguy** [tadashi-aikawa/obsidian-various-complements-plugin#165] opened 2022-09-03 05:47 UTC
![image](https://user-images.githubusercontent.com/67627057/188257682-a3fe2b2f-1b92-460d-9d85-ea228a47f83a.png)

Hi so I'm trying to enable various complements but it doesn't appear in the settings panel even after enabling it. There's no button to click for options either. When I click disable, it says "failed to unload plugin various-complements". Tried reinstalling also but no luck.

Is it incompatibility with the latest insider build maybe? Currently on 0.16.2

**Comment by tadashi-aikawa** [comment] 2022-09-03 06:01
@crazymedguy 
I couldn't reproduce it on Windows. Would you tell me the OS you are using?

**Comment by crazymedguy** [comment] 2022-09-03 06:04
Windows 11 actually. I don't think it's a plugin conflict either as i disabled all of them and re-enabled too. But here are some of what I'm using 

![image](https://user-images.githubusercontent.com/67627057/188258139-2f128327-8324-4f48-8741-2efde6db8da1.png)

**Comment by tadashi-aikawa** [comment] 2022-09-03 06:11
Thanks.

And I could reproduce it on the Sandbox vault. So I'll investigate it 👍

**Comment by tadashi-aikawa** [comment] 2022-09-03 06:30
Released in [v7.2.2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.2.2) 🚀 

Great thanks, @crazymedguy 🙏

**Closed by tadashi-aikawa** 2022-09-03 06:30 UTC
Labels: bug
