### ISSUE TITLE
bug: Too many quotation marks

### ISSUE THREAD

**Issue by MSzturc** [tadashi-aikawa/obsidian-various-complements-plugin#119] opened 2022-04-30 16:58 UTC
I have the following dict:

```
drop="<CARET>"	drop="<x> <y>"
drop="topleft"
drop="top"
drop="topright"
```

Which causes the following issue:

https://user-images.githubusercontent.com/4275753/166115005-68ac1119-fb70-4d1b-baa9-cb7a389f71c8.mov

I would expect that the last `"` after completion wont be displayed

**Comment by tadashi-aikawa** [comment] 2022-05-01 02:22
@MSzturc 
Thanks! I'll investigate it 👍

**Comment by tadashi-aikawa** [comment] 2022-05-01 03:52
This is not a bug. This plugin doesn't complete with removing existing input after the cursor. (Same as the JetBrains IDE's Enter behavior)

If it needs, it would be helpful to rename this issue as a Feature Request :)

**Comment by MSzturc** [comment] 2022-05-01 06:26
No, you don't have to, it was actually just a workaround.
My goal was to offer the user only valid input parameters.

Would it be possible to create hierarchies of dictionaries?

Something like this:

dropParametersDict.md

```
topleft
top
topright
```

and in the mainDictionary.md

```
drop="<dropParametersDict>"
```

**Comment by tadashi-aikawa** [comment] 2022-05-01 07:51
> Would it be possible to create hierarchies of dictionaries?

At least, I will not support the feature for the time being. The feature seems useful but has a significant impact.

**Comment by MSzturc** [comment] 2022-05-01 08:26
Yeah, if i was you i would want to support such a feature too. We could start it as undocumented feature and harden it in the upcoming weeks and in the end it will be a wonderful extension for all the plugin developers that want to give there users content assist.

**Comment by tadashi-aikawa** [comment] 2022-05-04 04:57
Let me close this issue because this is not a bug :)

**Closed by tadashi-aikawa** 2022-05-04 04:57 UTC
