### ISSUE TITLE
Is it possible to add Arabic?

### ISSUE THREAD

**Issue by osman1963** [tadashi-aikawa/obsidian-various-complements-plugin#2] opened 2021-02-09 04:34 UTC
Wow.. what a great plugin.. thank you so much
I was just wondering if you could add support for Arabic too.. you said in the plugin page in Obsidian that you would add new languages if anyone needs it.. so here I am taking the chance and asking for Arabic support.
Thanks in adavnce and keep up the great work

**Comment by tadashi-aikawa** [comment] 2021-02-10 06:18
Hi @osman1963!
Thank you for your FB and a feature request 😄 

It is probably possible if a tokenizer supports Arabic on JavaScript, But I couldn't find it. 😓 

If you know such a tokenizer, could you tell me?

**Comment by osman1963** [comment] 2021-02-16 22:59
Thank you Tadashi for your reply, and so sorry for my delayed response.
I'm so sorry but I'm not a programmer so I don't even know what a
tockenizer is. But I guess if you can find one for Persian it'll most
probably work with Arabic, since they share almost the same alphabet.

**Comment by tadashi-aikawa** [comment] 2021-02-18 00:33
Hi, @osman1963.

> I guess if you can find one for Persian it'll most
probably work with Arabic, since they share almost the same alphabet.

Thank you for the useful information! I will search it about not only Arabic but also Persian.

> I don't even know what a tockenizer is

The tokenizer is what divides sentences by words. For example, this message is tokenized by the tokenizer as follows. It is used to suggest words to be completed.

```
The | | tokenizer | | is | | what | | divides | | sentences | | by | | words | . | | For | | example | , | | this | | message | | is | | tokenized | | by | | the | | tokenizer | | as | | follows | . |
```

In the case of Arabic😢 

```
ع | ل | ى | س | بي | ل | ا | ل | مث | ا | ل | ، | ي | ت | م | ت | رم | ي | ز | ه | ذه | | ال | ر | سا | ل | ة | ب | وا | س | طة | | ال | ر | مز | | ال | م | مي | ز | ع | ل | ى | ا | لن | ح | و | ا | لت | ا | لي | . | ي | ت | م | ا | ست | خ | دا | م | ه | ل | اق | ت | را | ح | ا | ل | كل | م | ات | | ال | م | را | د | ا | س | تك | م | ال | ه | ا.
```

**Comment by tadashi-aikawa** [comment] 2021-02-21 03:30
Hi, @osman1963.

I have released v0.3.0, and it supports languages whose word break is whitespace. Maybe, it looks to be supporting Arabic, too. Could you confirm it?

**Comment by osman1963** [comment] 2021-02-21 14:43
I totally and fully and very gladly confirm it.. it works like a charm..
Words in Arabic are separated by spaces too..The only exception (which is
negligible as any arbic reader could identify it easily) is that the
conjunction 'and' is not separated by a space from the following word in
typing.

Thanks a million and thanks for clarifying what a tokenizer is.

**Comment by osman1963** [comment] 2021-02-21 14:46
Hi again Tadashi,
I also noticed that the plugin works also with any part of the world, i.e.
not necessarily the beginning of it - as is the case in MS word's autotext
for example..It is really magnificent
Thanks again :)

**Comment by tadashi-aikawa** [comment] 2021-02-22 01:39
Hi, @osman1963.

Thank you for testing!  I will close this issue.

> The only exception (which is
negligible as any arbic reader could identify it easily) is that the
conjunction 'and' is not separated by a space from the following word in
typing.

Thank you for telling me the exception! I am relieved that it can be negligible. I can't read Arabic without Google-transformer, so your advice is very beneficial for me.😄 

I want to improve this plugin for Obsidian and its users to more fun and handy. Please feel free to contact me if you have any ideas or questions. 😉

شكرا لك

**Comment by tadashi-aikawa** [comment] 2021-02-22 01:40
Fixed `v0.3.0`

**Closed** 2021-02-22 01:40 UTC
Labels: enhancement

**Comment by osman1963** [comment] 2021-02-28 22:11
Hi Tadashi
Thanks for the awesome plugin, and for your so kind response and prompt
action.
I have a  couple of ideas for this plugin and an idea for a new (much
needed) plugin.
For this one:
1. If you can trim the comma, semi-colon and dot at the end of the word
that would be great.
2. If you can make this feature global, i.e. application-level it would be
awesome. But of course in this case it won't suggest
the completion automatically, the user will have to tell the plugin to use
it.. Just the same way the Auto-text feature works in MS-Word.

Now for the new plugin idea
It is autocompletion for tags. I mean allow typing part of the tag to
suggest ones contained as child tags not the main one only.
example:
We already have #Grandfather/children/Son, #Grandfather/children/Daughter

If I start typing #ch it will give me suggestion of both these tags.
Alternatively one can type few letters and press a shortcut key to see
suggested tags (i.e. tags containing these letters) then the user can chose
or type a completely new tag.

I don't know if any of these ideas is doable, but I took advantage of your
kindness and gave it a shot.
Thanks again, and have a lovely day :)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tadashi-aikawa** [comment] 2021-03-01 01:12
Hi,  @osman1963.

Thank you for your ideas! I have questions about them; thus, I would ask one by one.

> If you can trim the comma, semi-colon and dot at the end of the word
that would be great.

Could you tell me the example which doesn't trim them? In English, I couldn't find the example as far as I know.

(It looks fine.)

https://user-images.githubusercontent.com/9500018/109440604-32af2200-7a76-11eb-86a9-b044f440eb38.mp4


Best regards.

**Comment by osman1963** [comment] 2021-03-01 12:45
[image: image.png]

[image: image.png]
Hi  Tadashi,

Thank you for your prompt reply.

That's very true for English, but for Arabic it keeps the comma, dot.. as
shown in the two pictures above.. Arabic, as you know, is written from
right to left, and the comma is like an inverted English comma, which
appears at the end of the second picture. My guess it is due to the use of
the tool that uses the space between words to tell when the word ends. If
that's the case and this issue is difficult to solve or undoable, don't
worry about it, the plugin as it is now is formidable. This was just a
touch of embellishment for Arabic, that's all, and any Arabic reader can
easily notice and deal with it.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tadashi-aikawa** [comment] 2021-03-03 14:11
Hi, @osman1963.

Unfortunately, I couldn't look at the images you uploaded. However, I probably understood what you said.

If trimming three symbols as follows is your expected, I may be able to deal with this feature. 😃 

- comma means `،`
  - https://unicode-table.com/en/060C/
- semicolon means `؛`
  - https://unicode-table.com/en/061B/
- dot means `ٜ`
  - https://unicode-table.com/en/065C/

Please let me know if there are any omissions and/or errors.

**Comment by tadashi-aikawa** [comment] 2021-03-03 23:34
Thanks, @osman1963 !

I have created an issue https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/5. I surveyed some Arabic sentences, and I couldn't found what use the dot ` ٜ`. So excluded it from the target.

**Comment by osman1963** [comment] 2021-03-04 13:39
That would be fine of course Tadashi.
Just to clarify how the dot is used in Arabic (one can very easily not
notice it), I'm attaching a picture showing it.

Thanks for the great work and enthusiasm.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tadashi-aikawa** [comment] 2021-03-06 04:08
Hi, @osman1963.

I still couldn't look at the pictures you uploaded as follows. Could you tell me a text instead of a picture?

![image](https://user-images.githubusercontent.com/9500018/110194686-f5370400-7e7c-11eb-8920-bb6cec5afde8.png)

Best regards.

**Comment by osman1963** [comment] 2021-03-07 21:31
Hi Tadashi.

هذا كلام جميل.
Here the dot is clear at the end (very left) I hope. If not, please let me
know.

**Comment by tadashi-aikawa** [comment] 2021-03-10 04:04
Hi, @osman1963. Thank you for example. 😄 

The dot looks like as same as used in English. So it didn't seem to be a problem as far as I tried to reproduced. Thus, for the time beginning, I will solve Issue #5 and release it.

**Comment by osman1963** [comment] 2021-03-10 11:52
😄😄 Great news

**Comment by tadashi-aikawa** [comment] 2021-03-13 09:25
Hi, @osman1963.

I have released v0.4.0 and added a new command, `Auto Complete as Arabic.` Please use it instead of `Auto Complete` and confirm it works as you expected or not.

Best regards.

**Comment by osman1963** [comment] 2021-03-13 14:56
Hi Tadashi.

Just checked it, works perfect 😄😄 thanks a lot

**Comment by tadashi-aikawa** [comment] 2021-03-14 02:33
Thank you for your check. 😉
