### ISSUE TITLE
FR: Make suggestions confirmable only after pressing the key to make a selection.

### ISSUE THREAD

**Issue by L7Cy** [tadashi-aikawa/obsidian-various-complements-plugin#243] opened 2023-08-19 03:14 UTC
I use the Enter key to confirm suggestions, but I often accidentally confirm a suggestion when I want to enter a new line at the end of a line. For example, if I type the word "常温" and then type a new line at the end of the line, I accidentally confirm the suggestion "常温常圧超伝導".

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/84382631/924ff10d-a507-442c-b7e4-a7c1028dd906

In the video, I'm using Google Japanese Input, but with Google Japanese Input, the suggestion cannot be confirmed until a selection key (such as Tab or Space) is pressed. Is there a way in this plugin to make suggestions confirmable only when a selection key is pressed? If not, I would be grateful if you could add this feature. 🙇‍♂️

**Comment by tadashi-aikawa** [comment] 2023-08-19 04:21
Hi, @L7Cy :)

I think you could turn off the [Complement automatically](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20Complement%20automatically/) option and use the [Show suggestions](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Show%20suggestions/) command.

**Comment by L7Cy** [comment] 2023-08-19 04:42
It is true that the problem can be solved in that way, but since it is convenient to have suggestions appear automatically, I don't want to disable the "Complement automatically" option.

**Comment by tadashi-aikawa** [comment] 2023-08-19 05:19
@L7Cy 
How about [Select a suggestion key](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.3.%20Key%20customization/%E2%9A%99%EF%B8%8F%20Select%20a%20suggestion%20key/) ? You could use many keys instead of "Enter".

**Comment by L7Cy** [comment] 2023-08-19 05:38
Of course I know I can select other keys, and I've set and used Cmd+Enter before, but the suggestion feature provided by Obsidian requires the use of the Enter key, which is confusing to me.😵

**Comment by tadashi-aikawa** [comment] 2023-08-19 05:50
@L7Cy 
Got it.

After all, Obsidian and Various Complements cannot determine whether the user wants a line break or not. I think triggering a single key before displaying a suggestion would not fundamentally solve the problem, as it would only make it more cumbersome to do so each time.

**Comment by L7Cy** [comment] 2023-08-19 06:43
There's no need to determine whether the user wants a line break or not. The problem is that the top item is already selected when the suggestion is displayed. I just want to select the "do not select" from the suggestions. With Google Japanese Input, I can choose whether or not to select from the suggestions by pressing or not pressing the key to select. I have never found this to be cumbersome.

**Comment by tadashi-aikawa** [comment] 2023-08-19 08:18
@L7Cy 
OK. I got it that your FR is "Don't focus the first suggestion until pushing 'cycle throw suggestions keys'".

I’m unsure if it’s possible, but I’ll survey and consider it👍

**Comment by tadashi-aikawa** [comment] 2023-08-19 13:20
@L7Cy 
I have surveyed it. Unfortunately, It is not easy for the current version of Obsidian. Let me add the `long-term` label to this issue.

**Comment by tadashi-aikawa** [comment] 2023-08-19 14:38
@L7Cy
I came up with a tricky idea that might enable the implementation of this feature🛀 

I'll try it tomorrow.

**Comment by tadashi-aikawa** [comment] 2023-08-20 04:41
LGTM on my settings 👀 

![2023-08-20-13-40-49](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/9a337e7e-0043-405b-92ec-97b0c5ebb3a2)

**Comment by tadashi-aikawa** [comment] 2023-08-20 07:07
@L7Cy 
Released in [v8.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.4.0) 🚀 

Please let me know if you have any concerns or issues.

**Closed by tadashi-aikawa** 2023-08-20 07:07 UTC
Labels: enhancement

**Comment by L7Cy** [comment] 2023-08-20 07:59
Amazing!! Thank you!🙏
However, I have one small concern. When typing a word that starts with Hiragana, such as "こうもり問題", I think there are times when you might confirm it as it is without selecting in IME, but at the same time as confirming, the suggestions will no longer be displayed.


https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/84382631/3b20da8e-037e-45ec-87d1-0c3df9a22554

**Comment by tadashi-aikawa** [comment] 2023-08-20 08:28
@L7Cy 
Not reproduce it on Microsoft IME. I'll download Google日本語入力 and survey it.

**Comment by tadashi-aikawa** [comment] 2023-08-20 08:40
@L7Cy 
Unfortunately, I couldn't reproduce it even I used Google日本語入力. Could you tell me the reproduction steps in the sandbox vault?

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/c522829e-c6c1-4896-aee9-cbfde688dc94

**Comment by L7Cy** [comment] 2023-08-20 09:08
I was able to reproduce this by enabling "No auto-focus until the cycle", creating a wikilink to the "こうもり問題" in any note, and confirming after typing "こうもり". My environment is MacOS, so this may be a MacOS-specific problem.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/84382631/f955b860-0715-4107-b357-af5f1949a889

**Comment by tadashi-aikawa** [comment] 2023-08-20 09:18
@L7Cy 
Thanks :)

> My environment is MacOS, so this may be a MacOS-specific problem.

I think so, too. Did you press the Enter key before confirming "こうもり" ?

**Comment by L7Cy** [comment] 2023-08-20 09:28
The Enter key is only pressed to confirm.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/84382631/0572f0ea-043a-4def-b2f7-10ac1d7b8c2a

**Comment by tadashi-aikawa** [comment] 2023-08-20 09:34
@L7Cy 
Thank you for your quick response!

Probably, I could fix the issue, so I will release it as v8.4.1 soon 👍 

( But I have no macOS environment.. so it would be great if you confirm it after the next release🙏 )

**Comment by tadashi-aikawa** [comment] 2023-08-20 09:37
@L7Cy 
Released in [v8.4.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.4.1) 🙏🙏

**Comment by L7Cy** [comment] 2023-08-20 10:06
It seems to be working fine! Thanks!!🙏

**Comment by tadashi-aikawa** [comment] 2023-08-20 10:12
I’m glad to hear that! Thanks!
