### ISSUE TITLE
Filter out duplicates

### ISSUE THREAD

**Issue by michalzmuda** [tadashi-aikawa/obsidian-various-complements-plugin#278] opened 2024-01-27 08:54 UTC
I would like to request the implementation of a feature to filter out duplicate entries from the popup. This enhancement would improve the user experience by ensuring that only unique information is displayed in the popup. Thank you for your consideration and continued work on this excellent plugin.

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/5843281/70adde9d-e99a-41be-876c-a24e90b5977c)

**Comment by tadashi-aikawa** [comment] 2024-01-27 12:07
Hi, @michalzmuda :)

That's quite unexpected. It's not behaving as expected, and I couldn't reproduce the issue in my vault.

Could you provide the steps to reproduce the issue in the sandbox vault?

**Comment by michalzmuda** [comment] 2024-01-28 11:22
@tadashi-aikawa I prepared the vault for you to reproduce bug.

Try to use "awo" and result awokado.

It looks like it has problem with indexing CRLF/LF line endings. Check the white spaces in the notepad++ for example. Please trim CRLF in the index because in also paste CRLF when I select the "awokado".

[duplicates.zip](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/files/14075793/duplicates.zip)

Thanks
Michal

**Comment by tadashi-aikawa** [comment] 2024-02-04 05:40
@michalzmuda 
Thank you for sharing the Vault :)

Unfortunately, I was unable to reproduce the issue of duplicate displays. 'awokado' was displayed as a candidate only once.

Additionally, upon checking the newline character in notepad.exe, they were all LF. Could there be any issues with my verification method or understanding?

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/ed6f65ed-0f96-4ddf-9a25-aeead36b877d)

**Comment by michalzmuda** [comment] 2024-02-05 19:25
@tadashi-aikawa 

Thanks for checking. I've double check this behavior. It looks like Obsidian changes line endings. 
I've uploaded new vault. 

Steps to reproduce:
- open vault
- don't open any file, just test.md
- type "awo"

Result:
![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/5843281/e96cd8ec-eecf-4677-b014-12542ee9c682)

Vault with the bug.
[duplicates_new.zip](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/files/14170965/duplicates_new.zip)
duplicates\Rak.md - windows style line endings
duplicates\Tłuszcze.md - unix style line endings.

Thanks,
Michal

**Comment by tadashi-aikawa** [comment] 2024-02-17 05:11
Thank you, @michalzmuda :)

I was able to reproduce the issue. It only occurs when the strategy is set to either "default" or "arabic".

**Comment by tadashi-aikawa** [comment] 2024-02-17 05:29
@michalzmuda 
Released in [v9.2.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.2.1) 🚀

**Closed by tadashi-aikawa** 2024-02-17 05:29 UTC
Labels: wait for visitor's action
