### ISSUE TITLE
Icon showing type to suggestion not showing

### ISSUE THREAD

**Issue by TimothyBesada** [tadashi-aikawa/obsidian-various-complements-plugin#188] opened 2022-12-15 01:32 UTC
For some reason, there is no icon showing up telling me what suggestion I'm getting. So it's hard to know if I'm including a link or if the word is found in another file etc.

![image](https://user-images.githubusercontent.com/15740296/207751507-29199df4-c24f-4bbc-be00-114ba30ad4d4.png)

**Comment by tadashi-aikawa** [comment] 2022-12-17 11:52
Hi, @TimothyBesada :)

> For some reason, there is no icon showing up telling me what suggestion I'm getting

I want to know the reason. So could you tell me the way to reproduce it in the sandbox vault?

**Comment by TimothyBesada** [comment] 2022-12-17 12:45
Hi,

I reinstalled the plugin to figure out how to reproduce it, but after doing that it seems to work as intended. 

I'll let you know if the problem shows up again :).

**Comment by tadashi-aikawa** [comment] 2022-12-21 22:51
@TimothyBesada 
I got it :) I will close this issue. If you show the problem again, please reopen it 👍

**Closed by tadashi-aikawa** 2022-12-21 22:51 UTC
